[package]
name = "git-dive"
description = "Dive into a file's history to find root cause"
version = "0.0.1"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gitext-rs/git-dive"
documentation = "https://github.com/gitext-rs/git-dive"
readme = "README.md"
categories = ["command-line-interface", "development-tools"]
keywords = ["git", "cli"]
edition = "2021"
rust-version = "1.64.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/gitext-rs/git-dive/compare/{{tag_name}}...HEAD", exactly=1},
]

[dependencies]
git2 = { version = "0.15", default-features = false, features = ["vendored-libgit2"] }
clap = { version = "4.1.4", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "2.0"
log = "0.4"
env_logger = { version = "0.10", default-features = false, features = ["color"] }
concolor = "0.1.1"
concolor-clap = { version = "0.1.0", features = ["api"] }
proc-exit = "2"
human-panic = "1"
anyhow = "1.0.68"
syntect = { version = "5.0.0", default-features = false, features = ["parsing", "regex-fancy"] }
terminal_size = "0.2.3"
textwrap = "0.16.0"
anstyle = "0.3.1"
anstyle-stream = "0.2.2"
is-terminal = "0.4.4"
content_inspector = "0.2.4"
encoding = "0.2.33"
git-config-env = "0.1.2"
shlex = "1.1.0"
anstyle-syntect = "0.2.0"
bincode = "1.3.3"
serde = { version = "1.0.152", features = ["derive"] }
flate2 = "1.0.25"
once_cell = "1.17.0"
bugreport = "0.5.0"
